api_platform:
  defaults:
    stateless: true
    pagination_enabled: true
    pagination_items_per_page: 10
    pagination_client_items_per_page: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  collection:
    order: "ASC"
    order_parameter_name: "sort"
    pagination:
      items_per_page_parameter_name: "itemsPerPage"

  path_segment_name_generator: SIP\Core\SingularPathSegmentNameGenerator
  title: Sistim Informasi Paroki
  version: 1.0.0
  # Mercure integration, remove if unwanted
  #mercure: ~
  # Good cache defaults for REST APIs
