api_platform:
    defaults:
        stateless: true
        pagination_items_per_page: 10
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]

    path_segment_name_generator: SIP\Core\SingularPathSegmentNameGenerator
    mapping:
        paths:
            - '%kernel.project_dir%/src/Security/Entity'
    title: Sistim Informasi Paroki
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
