api_platform:
  title: Sistim Informasi Paroki API
  version: 1.0.0
  # Mercure integration, remove if unwanted
  #mercure:
  # Good cache defaults for REST APIs
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    pagination_enabled: true
    pagination_items_per_page: 10
    pagination_client_items_per_page: true
  collection:
    order: "ASC"
    order_parameter_name: "sort"
    pagination:
      items_per_page_parameter_name: "itemsPerPage"

  path_segment_name_generator: SIP\Core\SingularPathSegmentNameGenerator

when@test:
#  mercure:
#    enabled: false
#    hub_url: null
