lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    token_extractors:
        # look for a token as Authorization Header
        #authorization_header:
        #    enabled: true
        #    prefix:  Bearer
        #    name:    Authorization
        cookie:
            enabled: true
            name: '%env(COOKIE_BEARER)%'
        
    set_cookies:
        BEARER:
            samesite: strict
            path: "/"
            #domain: "localhost:3000"
            secure: true
            httpOnly: true
