fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

auth_login:
    path: /auth/login
    methods: ['POST']
    options:
        expose: true

security_controller:
    resource:
        path: ../src/Security/Controller/
        namespace: SIP\Security\Controller
    type: attribute
