services:
  _defaults:
    autowire: true
    autoconfigure: true

  SIP\Tests\Behat\:
    resource: "../tests/Behat/*"
    exclude:
      - "../tests/Behat/Resources"

#  mercure.hub.default:
#    class: SIP\Tests\Behat\Mercure\HubStub.php
